/**
 * Provenance sidecar loader — the data layer behind "click a number,
 * see its source chain".
 *
 * Sidecars are generated by pipeline/src/publish/provenance.py, which
 * recomputes every integrity check against the published JSONs at
 * generation time (fail-closed). This module only reads them.
 *
 * Domains adopt provenance incrementally: loaders resolve to null when
 * a domain has no sidecar yet, so UI callers can render nothing rather
 * than error.
 */

import { useEffect, useState } from 'react';

export interface ProvenanceStep {
  kind: 'document' | 'api' | 'check';
  name: string;
  publisher?: string;
  url?: string;
  retrieved?: string;
  status?: 'pass';
}

export interface ProvenanceFigure {
  value: number;
  unit: string;
  label: string;
  chain: ProvenanceStep[];
  basis?: string;
}

export interface ProvenanceSidecar {
  domain: string;
  year: string;
  generated: string;
  spec: number;
  figures: Record<string, ProvenanceFigure>;
}

const cache = new Map<string, ProvenanceSidecar | null>();
const inflight = new Map<string, Promise<ProvenanceSidecar | null>>();

/** Load a domain's provenance sidecar; null if the domain has none yet. */
export function loadProvenance(
  domain: string,
  year: string,
): Promise<ProvenanceSidecar | null> {
  const key = `${domain}/${year}`;
  if (cache.has(key)) return Promise.resolve(cache.get(key) ?? null);
  const pending = inflight.get(key);
  if (pending) return pending;

  const promise = fetch(`/data/${domain}/${year}/provenance.json`)
    .then((res) => (res.ok ? (res.json() as Promise<ProvenanceSidecar>) : null))
    .catch(() => null)
    .then((sidecar) => {
      cache.set(key, sidecar);
      inflight.delete(key);
      return sidecar;
    });
  inflight.set(key, promise);
  return promise;
}

/**
 * Hook: provenance for one figure, e.g.
 *   useProvenance('budget', '2025-26', 'summary.totalExpenditure')
 * Returns null while loading and for domains/figures without provenance.
 */
export function useProvenance(
  domain: string,
  year: string,
  figureKey: string,
): ProvenanceFigure | null {
  const [figure, setFigure] = useState<ProvenanceFigure | null>(null);

  useEffect(() => {
    let alive = true;
    loadProvenance(domain, year).then((sidecar) => {
      if (alive) setFigure(sidecar?.figures[figureKey] ?? null);
    });
    return () => {
      alive = false;
    };
  }, [domain, year, figureKey]);

  return figure;
}
