/**
 * Maps every DomainDataKey to its loader function + year.
 * Used by useTopicData to resolve which JSON files to fetch.
 */

import type { DomainDataKey } from './topicConfig.ts';
import {
  loadSummary,
  loadReceipts,
  loadExpenditure,
  loadSankey,
  loadTreemap,
  loadStatewise,
  loadSchemes,
  loadBudgetTrends,
  loadBudgetVsActual,
  loadEconomySummary,
  loadGDPGrowth,
  loadInflation,
  loadFiscal,
  loadExternal,
  loadSectors,
  loadIndicators,
  loadRBISummary,
  loadMonetaryPolicy,
  loadLiquidity,
  loadCredit,
  loadForex,
  loadRBIIndicators,
  loadStatesSummary,
  loadGSDP,
  loadStateRevenue,
  loadFiscalHealth,
  loadStatesIndicators,
  loadCensusSummary,
  loadPopulation,
  loadLiteracyData,
  loadDemographics,
  loadHealthData,
  loadCensusIndicators,
  loadEducationSummary,
  loadEnrollment,
  loadQuality,
  loadSpending,
  loadEducationIndicators,
  loadEmploymentSummary,
  loadUnemployment,
  loadParticipation,
  loadSectoral,
  loadEmploymentIndicators,
  loadHealthcareSummary,
  loadInfrastructure,
  loadHealthSpending,
  loadDisease,
  loadHealthcareIndicators,
  loadEnvironmentSummary,
  loadAirQuality,
  loadForest,
  loadEnergy,
  loadWater,
  loadEnvironmentIndicators,
  loadElectionsSummary,
  loadTurnout,
  loadResults,
  loadCandidates,
  loadRepresentation,
  loadElectionsIndicators,
  loadCrimeSummary,
  loadCrimeOverview,
  loadWomenSafety,
  loadRoadAccidents,
  loadCybercrime,
  loadPolice,
  loadJustice,
  loadCrimeIndicators,
} from './dataLoader.ts';

interface LoaderEntry {
  loader: (year: string) => Promise<unknown>;
  year: string;
}

export const DOMAIN_DATA_MAP: Record<DomainDataKey, LoaderEntry> = {
  // Budget
  'budget/summary': { loader: loadSummary, year: '2025-26' },
  'budget/receipts': { loader: loadReceipts, year: '2025-26' },
  'budget/expenditure': { loader: loadExpenditure, year: '2025-26' },
  'budget/sankey': { loader: loadSankey, year: '2025-26' },
  'budget/treemap': { loader: loadTreemap, year: '2025-26' },
  'budget/statewise': { loader: loadStatewise, year: '2025-26' },
  'budget/schemes': { loader: loadSchemes, year: '2025-26' },
  'budget/trends': { loader: loadBudgetTrends, year: '2025-26' },
  'budget/budget-vs-actual': { loader: loadBudgetVsActual, year: '2025-26' },
  // Economy
  'economy/summary': { loader: loadEconomySummary, year: '2025-26' },
  'economy/gdp-growth': { loader: loadGDPGrowth, year: '2025-26' },
  'economy/inflation': { loader: loadInflation, year: '2025-26' },
  'economy/fiscal': { loader: loadFiscal, year: '2025-26' },
  'economy/external': { loader: loadExternal, year: '2025-26' },
  'economy/sectors': { loader: loadSectors, year: '2025-26' },
  'economy/indicators': { loader: loadIndicators, year: '2025-26' },
  // RBI
  'rbi/summary': { loader: loadRBISummary, year: '2025-26' },
  'rbi/monetary-policy': { loader: loadMonetaryPolicy, year: '2025-26' },
  'rbi/liquidity': { loader: loadLiquidity, year: '2025-26' },
  'rbi/credit': { loader: loadCredit, year: '2025-26' },
  'rbi/forex': { loader: loadForex, year: '2025-26' },
  'rbi/indicators': { loader: loadRBIIndicators, year: '2025-26' },
  // States
  'states/summary': { loader: loadStatesSummary, year: '2025-26' },
  'states/gsdp': { loader: loadGSDP, year: '2025-26' },
  'states/revenue': { loader: loadStateRevenue, year: '2025-26' },
  'states/fiscal-health': { loader: loadFiscalHealth, year: '2025-26' },
  'states/indicators': { loader: loadStatesIndicators, year: '2025-26' },
  // Census
  'census/summary': { loader: loadCensusSummary, year: '2025-26' },
  'census/population': { loader: loadPopulation, year: '2025-26' },
  'census/literacy': { loader: loadLiteracyData, year: '2025-26' },
  'census/demographics': { loader: loadDemographics, year: '2025-26' },
  'census/health': { loader: loadHealthData, year: '2025-26' },
  'census/indicators': { loader: loadCensusIndicators, year: '2025-26' },
  // Education
  'education/summary': { loader: loadEducationSummary, year: '2025-26' },
  'education/enrollment': { loader: loadEnrollment, year: '2025-26' },
  'education/quality': { loader: loadQuality, year: '2025-26' },
  'education/spending': { loader: loadSpending, year: '2025-26' },
  'education/indicators': { loader: loadEducationIndicators, year: '2025-26' },
  // Employment
  'employment/summary': { loader: loadEmploymentSummary, year: '2025-26' },
  'employment/unemployment': { loader: loadUnemployment, year: '2025-26' },
  'employment/participation': { loader: loadParticipation, year: '2025-26' },
  'employment/sectoral': { loader: loadSectoral, year: '2025-26' },
  'employment/indicators': { loader: loadEmploymentIndicators, year: '2025-26' },
  // Healthcare
  'healthcare/summary': { loader: loadHealthcareSummary, year: '2025-26' },
  'healthcare/infrastructure': { loader: loadInfrastructure, year: '2025-26' },
  'healthcare/spending': { loader: loadHealthSpending, year: '2025-26' },
  'healthcare/disease': { loader: loadDisease, year: '2025-26' },
  'healthcare/indicators': { loader: loadHealthcareIndicators, year: '2025-26' },
  // Environment
  'environment/summary': { loader: loadEnvironmentSummary, year: '2025-26' },
  'environment/air-quality': { loader: loadAirQuality, year: '2025-26' },
  'environment/forest': { loader: loadForest, year: '2025-26' },
  'environment/energy': { loader: loadEnergy, year: '2025-26' },
  'environment/water': { loader: loadWater, year: '2025-26' },
  'environment/indicators': { loader: loadEnvironmentIndicators, year: '2025-26' },
  // Elections
  'elections/summary': { loader: loadElectionsSummary, year: '2025-26' },
  'elections/turnout': { loader: loadTurnout, year: '2025-26' },
  'elections/results': { loader: loadResults, year: '2025-26' },
  'elections/candidates': { loader: loadCandidates, year: '2025-26' },
  'elections/representation': { loader: loadRepresentation, year: '2025-26' },
  'elections/indicators': { loader: loadElectionsIndicators, year: '2025-26' },
  // Crime
  'crime/summary': { loader: loadCrimeSummary, year: '2025-26' },
  'crime/overview': { loader: loadCrimeOverview, year: '2025-26' },
  'crime/women-safety': { loader: loadWomenSafety, year: '2025-26' },
  'crime/road-accidents': { loader: loadRoadAccidents, year: '2025-26' },
  'crime/cybercrime': { loader: loadCybercrime, year: '2025-26' },
  'crime/police': { loader: loadPolice, year: '2025-26' },
  'crime/justice': { loader: loadJustice, year: '2025-26' },
  'crime/indicators': { loader: loadCrimeIndicators, year: '2025-26' },
};
